### ISSUE TITLE
GPU pixel caching?

### ISSUE THREAD

**Issue by pitr-ch** [mame/optcarrot#12]
Hi @mame,

I've read your [presentation](http://www.slideshare.net/mametter/optcarrot-a-pureruby-nes-emulator) and I have a question about slide 16
![slide16](https://image.slidesharecdn.com/endoh-tokyo-rubykaigi-11-160528092023/95/optcarrot-a-pureruby-nes-emulator-16-638.jpg?cb=1464427336)

- Are the invalidated pixels still tracked. I could not find it in the source code. Could you point me to it?
- Did you investigate how this optimisation effects benchmarking? It could make the results vary depending on how much of the screen is changing.

**Comment by mame** [comment]
Good question.

The explanation is super-exaggerated.  In fact, Optcarrot have no screen buffer.  Instead, it caches an intermediate calculation result between VRAM and the screen.

For each pixel, GPU does three processes: (1) read values from VRAM and VROM, (2) perform some calculation with the values, and (3) decide the color and send it to the monitor.

Note that, unless VRAM changes, the result of (2) does not change.  Optcarrot performs (and caches) this calculation whenever VRAM changes, but not in per-pixel loop.  The per-pixel loop completely omits the processes (1) and (2), by reading the calculation result from the cache.


Here is the actual source code:

https://github.com/mame/optcarrot/blob/master/lib/optcarrot/ppu.rb#L481-L483

* The method `poke_2007` handles an update request to VRAM.
* `@name_ref` is an array of integer arrays that represents VRAM.
* `@name_lut` and `@attr_lut` are the caches that preserve the intermediate calculation result.

In essence, this method executes `@nmt_ref[addr >> 10 & 0x3][addr & 0x03ff] = data`, which alters a byte of VRAM.  Not only that, but it updates some bytes of `@name_lut` and `@attr_lut` that corresponding to the altered byte of VRAM.  I think that `@lut_update` maintains the correspondence between them.  (Sorry, I forgot the details.)

The optimization effects may vary, but I think that it will always work positively because GPU works much faster than CPU instructions.  While CPU updates one byte of VRAM, GPU handles at least several tens of pixels.  This optimization slightly degrades the performance of VRAM update, and improves GPU per-pixel task.  The latter is much more frequent than the former.  But I could be wrong, I just investigated some limited ROMs.

**Comment by pitr-ch** [comment]
Thanks you.
